### ISSUE TITLE
`rb.utils.impedance` returning NaNs in `survey-study.ipynb`

### ISSUE THREAD

**Issue by leomiquelutti** [BRGM/razorback#10]
I am trying to reproduce the `survey-study.ipynb` notebook from the tutorials. The `rb.utils.impedance` is returning an array of `NaN`s, either locally or in Google Colab.

### Reproducing code example:

It can be reproduced with [this Google Colab](https://colab.research.google.com/drive/1MV3TWVpX-_vjLOTAS1oixHDAtkM9cpyB?usp=sharing) adaptation. It also can be reproduced locally running [`survey-study.ipynb`](https://github.com/BRGM/razorback/blob/master/docs/source/tutorials/survey-study.ipynb) with [this data](https://github.com/BRGM/razorback-tutorial-data).

### Razorback/Python version information:

Locally, razorback version 0.4.0 under Windows with python 3.8.5.

**Comment by fsmaibrgm** [comment]
Hi @leomiquelutti, thanks for your feedback !

I just re-run locally the tutorial notebook with razorback-0.4.0. I obtained the expected results. So no problem on my side.

Did you applied the fix on the data path we discussed on the last issue ? see : https://github.com/BRGM/razorback/issues/7#issuecomment-906476556

**Comment by fsmaibrgm** [comment]
For a local run, in order to run the notebook without modifications, I create a symbolic link (`data`) in the directory of the notebook pointing to the data repository : 
```bash
$ ln -s path/to/razorback-tutorial-data/ data
$ ls
data  survey-study.ipynb
```

**Comment by fsmaibrgm** [comment]
I'm closing this issue because a solution has been proposed and no problems have been reported since.
@leomiquelutti, if you're still having trouble with this, we can reopen the issue.
