### ISSUE TITLE
Impedance cannot run with prefilter

### ISSUE THREAD

**Issue by Aaron2014** [BRGM/razorback#4]
Thank you so much for your sharing this wonderful code. I am still struggling with the prefilter. First, after upgrading to razorback-0.3.0.4, there is no bcoher_filter in the razorback.prefilters. I went into the file and found the bcoher_filter was changed to cod_filter. I got the same error when I had the prefilter on. Here are error messages of M-Estimator run. 

SignalSet: 9 channels, 1 run
tags: {'site004_Ex': (0,), 'site004_Ey': (1,), 
       'site004_Hx': (2,), 'site004_Hy': (3,), 
       'site004_Hz': (4,), 'site099_Hx': (5,), 
       'site099_Hy': (6,), 'site100_Hx': (7,), 
       'site100_Hy': (8,), 'B': (2, 3), 
       'E': (0, 1), 'Bremote': (6, 7, 5, 8)}
----------  -------------------  -------------------
  sampling                start                 stop
       128  2016-04-28 19:00:00  2016-04-29 07:00:00
----------  -------------------  -------------------
starting frequency 0.001
arrays used as indices must be of integer (or boolean) type
starting frequency 0.0012879
arrays used as indices must be of integer (or boolean) type
starting frequency 0.00165868
arrays used as indices must be of integer (or boolean) type
starting frequency 0.00213622
arrays used as indices must be of integer (or boolean) type
starting frequency 0.00275123
arrays used as indices must be of integer (or boolean) type
starting frequency 0.0035433
arrays used as indices must be of integer (or boolean) type
starting frequency 0.00456342
arrays used as indices must be of integer (or boolean) type
starting frequency 0.00587722
arrays used as indices must be of integer (or boolean) type
starting frequency 0.00756926
arrays used as indices must be of integer (or boolean) type
starting frequency 0.00974845
arrays used as indices must be of integer (or boolean) type
starting frequency 0.012555
arrays used as indices must be of integer (or boolean) type
starting frequency 0.0161696
arrays used as indices must be of integer (or boolean) type
starting frequency 0.0208248
arrays used as indices must be of integer (or boolean) type
starting frequency 0.0268202
arrays used as indices must be of integer (or boolean) type
starting frequency 0.0345417
arrays used as indices must be of integer (or boolean) type
starting frequency 0.0444862
arrays used as indices must be of integer (or boolean) type
starting frequency 0.0572938
arrays used as indices must be of integer (or boolean) type
starting frequency 0.0737886
arrays used as indices must be of integer (or boolean) type
starting frequency 0.0950322
arrays used as indices must be of integer (or boolean) type
starting frequency 0.122392
arrays used as indices must be of integer (or boolean) type
starting frequency 0.157628
arrays used as indices must be of integer (or boolean) type
starting frequency 0.203009
arrays used as indices must be of integer (or boolean) type
starting frequency 0.261455
arrays used as indices must be of integer (or boolean) type
starting frequency 0.336728
arrays used as indices must be of integer (or boolean) type
starting frequency 0.433672
arrays used as indices must be of integer (or boolean) type
starting frequency 0.558525
arrays used as indices must be of integer (or boolean) type
starting frequency 0.719324
arrays used as indices must be of integer (or boolean) type
starting frequency 0.926416
arrays used as indices must be of integer (or boolean) type
starting frequency 1.19313
arrays used as indices must be of integer (or boolean) type
starting frequency 1.53663
arrays used as indices must be of integer (or boolean) type
starting frequency 1.97902
arrays used as indices must be of integer (or boolean) type
starting frequency 2.54878
arrays used as indices must be of integer (or boolean) type
starting frequency 3.28257
arrays used as indices must be of integer (or boolean) type
starting frequency 4.22762
arrays used as indices must be of integer (or boolean) type
starting frequency 5.44475
arrays used as indices must be of integer (or boolean) type
starting frequency 7.01229
arrays used as indices must be of integer (or boolean) type
starting frequency 9.03112
arrays used as indices must be of integer (or boolean) type
starting frequency 11.6312
arrays used as indices must be of integer (or boolean) type
starting frequency 14.9798
arrays used as indices must be of integer (or boolean) type
starting frequency 19.2924
arrays used as indices must be of integer (or boolean) type
starting frequency 24.8467
arrays used as indices must be of integer (or boolean) type
starting frequency 32
arrays used as indices must be of integer (or boolean) type
(42, 2, 2)

**Comment by fsmaibrgm** [comment]
Can you join the code in addition to the terminal output ?

**Comment by Aaron2014** [comment]
Thank you so much. Here is the script I used. 
[Survey_study.zip](https://github.com/BRGM/razorback/files/5895476/Survey_study.zip)

**Comment by fsmaibrgm** [comment]
The problem seems to appears with numpy 1.19.
The computation works fine with numpy 1.18.

I will fix the bug soon.

**Comment by Aaron2014** [comment]
Thank you so much. I used Python 3.9 and I see you ran the code on Jupyter. Could this be another possible issue? 
I see there is a function called "prefilter", for example, in "utils.py" Line 310. I tried to find where this function is, but didn't find it. I searched online, this is a function of IPython (Jupyter), but not in Python. But I am not fully sure this is an issue and I don't want to mislead you. Again, thank you so much for sharing your wonderful code and for debugging this issue.

**Comment by fsmaibrgm** [comment]
> Thank you so much. I used Python 3.9 and I see you ran the code on Jupyter. Could this be another possible issue?

Not a problem

> I see there is a function called "prefilter", for example, in "utils.py" Line 310. I tried to find where this function is, but didn't find it. I searched online, this is a function of IPython (Jupyter), but not in Python.

Look at line 296, you'll see that `prefilter` is an argument of the function. So no problem here.

If you want to see the script working before the fix is published, you can `pip install numpy==1.18` to switch to the older version of numpy, with which razorback was tested.

Again, a bug fix will come to make razorback works with numpy 1.19+

**Comment by fsmaibrgm** [comment]
The new release (0.3.0.5) should fix the problems you found.
Update the library to test it : `pip install -U razorback`

**Comment by Aaron2014** [comment]
Thank you so much. Really appreciate.

**Comment by fsmaibrgm** [comment]
I'm closing the issue.
Thanks for the feedback.

Please add a comment here if you think the problem persists.
