### ISSUE TITLE
How to read time-series data from text file?

### ISSUE THREAD

**Issue by chdwql** [BRGM/razorback#6]
How to read time-series data from text file?

**Comment by fsmaibrgm** [comment]
A text file is not a very specific description of your data. Thus the answer depends on your actual data file formatting.

Razorback needs at least 3 informations to build a time serie : 1/ the array of values, 2/ the sampling rate and 3/ the start time.
(If applicable, a calibration function can also be provided).

```python
import numpy as np
import razorback as rzb

array = np.random.rand(100)  # 100 random values for the example
sampling = 10  # sampling rate in Hz
start = 0  # start time in seconds
signal = rzb.SyncSignal([array], sampling, start)
```

If your text file is only a storage for the array of values and you know the sampling rate by an other mean, then the example above can be adapted by using `np.loadtxt`.
Here `"your-time-serie.txt"` is a file that contains one line (or one column) of numbers and nothing else.
```python
import numpy as np
import razorback as rzb

array = np.loadtxt("your-time-serie.txt")  # loading the raw data of ONE time serie
sampling = 10  # sampling rate in Hz
start = 0  # start time in seconds
signal = rzb.SyncSignal([array], sampling, start)
```

Again,this solution must be adapted according to your actual file formatting.

**Comment by chdwql** [comment]
OK, thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Farid ***@***.***&gt;; 
发送时间: 2021年6月9日(星期三) 下午4:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BRGM/razorback] How to read time-series data from text file? (#6)





 
A text file is not a very specific description of your data. Thus the answer depends on your actual data file formatting.
 
Razorback needs at least 3 informations to build a time serie : 1/ the array of values, 2/ the sampling rate and 3/ the start time.
 (If applicable, a calibration function can also be provided).
 import numpy as np import razorback as rzb array = np.random.rand(100)  # 100 random values for the example sampling = 10  # sampling rate in Hz start = 0  # start time in seconds signal = rzb.SyncSignal([array], sampling, start)
 
If your text file is only a storage for the array of values and you know the sampling rate by an other mean, then the example above can be adapted by using np.loadtxt.
 Here "your-time-serie.txt" is a file that contains one line (or one column) of numbers and nothing else.
 import numpy as np import razorback as rzb array = np.loadtxt("your-time-serie.txt")  # loading the raw data of ONE time serie sampling = 10  # sampling rate in Hz start = 0  # start time in seconds signal = rzb.SyncSignal([array], sampling, start)
 
Again,this solution must be adapted according to your actual file formatting.
