### ISSUE TITLE
Processing Phoenix Geophysics data using Razorback ?

### ISSUE THREAD

**Issue by melaimmohamedanis** [BRGM/razorback#9]
hello
I have data  collected from a survey   using Phoenix Geophysics MT station (MTU-5A)
I want to process this data using Razorback
my question:  is there a script or tutorial explaining how can I process my data using Razorback?

**Comment by JulianGrodzicky** [comment]
This might help:
https://www.frontiersin.org/articles/10.3389/feart.2020.00296/full

https://www.mtnet.info/EMinars/20210127_WawrzyniakSmai_EMinar.pdf

https://razorback.readthedocs.io/en/latest/

https://www.youtube.com/watch?v=b75_BZR4D_I

Not sure about this one:
https://library.seg.org/doi/abs/10.1190/geo2013-0026.1

Cheers,
Julian






    On Wednesday, 5 January 2022, 01:02:07 am AEDT, melaimmohamedanis ***@***.***> wrote:  
 
 


hello
I have data collected from a survey using Phoenix Geophysics MT station (MTU-5A)
I want to process this data using Razorback
my question: is there a script or tutorial explaining how can I process my data using Razorback?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JulianGrodzicky** [comment]
And you also might need:
Mtpy - Google Search


| 
| 
|  | 
Mtpy - Google Search


 |

 |

 |




    On Wednesday, 5 January 2022, 01:02:07 am AEDT, melaimmohamedanis ***@***.***> wrote:  
 
 


hello
I have data collected from a survey using Phoenix Geophysics MT station (MTU-5A)
I want to process this data using Razorback
my question: is there a script or tutorial explaining how can I process my data using Razorback?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fsmaibrgm** [comment]
Razorback does not provide for now a function for loading phoenix files.
This is because we are not working yet with such data.

If you are able to load by yourself the raw signal, the sampling rate, the start time and the calibration of each run/channel, then you can directly instantiate `razorback.SyncSignal`.
Once you have your instances of `razorback.SyncSignal`, the following will not depend on the original file format.

You can look at the tutorials to see what to do from there:
- https://razorback.readthedocs.io/en/latest/tutorials/handling-time-series.html
- https://razorback.readthedocs.io/en/latest/tutorials/survey-study.html

**Comment by melaimmohamedanis** [comment]
> This might help: https://www.frontiersin.org/articles/10.3389/feart.2020.00296/full https://www.mtnet.info/EMinars/20210127_WawrzyniakSmai_EMinar.pdf https://razorback.readthedocs.io/en/latest/ https://www.youtube.com/watch?v=b75_BZR4D_I Not sure about this one: https://library.seg.org/doi/abs/10.1190/geo2013-0026.1 Cheers, Julian On Wednesday, 5 January 2022, 01:02:07 am AEDT, melaimmohamedanis ***@***.***> wrote: hello I have data collected from a survey using Phoenix Geophysics MT station (MTU-5A) I want to process this data using Razorback my question: is there a script or tutorial explaining how can I process my data using Razorback? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

thank you  Mr. JulianGrodzicky for your help, I will prepare a code that extracts the information needed in Razorback, from Pheonix txt.data .

**Comment by melaimmohamedanis** [comment]
> Razorback does not provide for now a function for loading phoenix files. This is because we are not working yet with such data.
> 
> If you are able to load by yourself the raw signal, the sampling rate, the start time and the calibration of each run/channel, then you can directly instantiate `razorback.SyncSignal`. Once you have your instances of `razorback.SyncSignal`, the following will not depend on the original file format.
> 
> You can look at the tutorials to see what to do from there:
> 
> * https://razorback.readthedocs.io/en/latest/tutorials/handling-time-series.html
> * https://razorback.readthedocs.io/en/latest/tutorials/survey-study.html

hello sir
thank you for your help 
there are programs in Pheonix geophysics that converts all data needed in .txt files 
I will work on these files.

**Comment by fsmaibrgm** [comment]
> > Razorback does not provide for now a function for loading phoenix files. This is because we are not working yet with such data.
> > If you are able to load by yourself the raw signal, the sampling rate, the start time and the calibration of each run/channel, then you can directly instantiate `razorback.SyncSignal`. Once you have your instances of `razorback.SyncSignal`, the following will not depend on the original file format.
> > You can look at the tutorials to see what to do from there:
> > 
> > * https://razorback.readthedocs.io/en/latest/tutorials/handling-time-series.html
> > * https://razorback.readthedocs.io/en/latest/tutorials/survey-study.html
> 
> hello sir thank you for your help there are programs in Pheonix geophysics that converts all data needed in .txt files I will work on these files.

That seems reasonable to me.
There might be some hints in #6.
Do not hesitate to ask more specific questions here if needed.
